<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item; // Pastikan namespace model benar
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('items')->delete(); // Hati-hati, ini akan menghapus item_keywords juga jika ada cascade

        $itemsData = [
            // Daikin (Brand ID 1) - 5 items
            [
                'name' => 'Daikin FTV15AXV14 Lite Series',
                'price' => 3550000.00,
                'description' => 'AC Split 1/2 PK Standard R32, kapasitas pendinginan 5000 BTU/h, konsumsi daya listrik 380 Watt. Mode Turbo. Garansi Kompresor 3 tahun.',
                'category_id' => 4,
                'brand_id' => 1,
                'stock' => 15,
                'img' => 'daikin_ftv15.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTV15A',
                'main_attribute_1_name' => 'Garansi',
                'main_attribute_1_value' => '3 Tahun Kompresor',
                'main_attribute_2_name' => 'Ukuran Ruangan',
                'main_attribute_2_value' => '6-10 m²',
                'main_attribute_3_name' => 'Filter Udara',
                'main_attribute_3_value' => 'Standar Anti Debu',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 380,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Daikin FTKQ25UVM4 Star Inverter',
                'price' => 5450000.00,
                'description' => 'AC Split 1 PK Star Inverter R32. Kapasitas 8500 BTU, daya listrik 810 Watt. Hemat Listrik rating Bintang 4 CSPF. Gin-Ion Filter. Mode Low Watt.',
                'category_id' => 6,
                'brand_id' => 1,
                'stock' => 10,
                'img' => 'daikin_ftkq25.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTKQ25U',
                'main_attribute_1_name' => 'Rating Energi',
                'main_attribute_1_value' => 'Bintang 4 CSPF',
                'main_attribute_2_name' => 'Filter Canggih',
                'main_attribute_2_value' => 'Gin-Ion Anti Bakteri',
                'main_attribute_3_name' => 'Mode Operasi',
                'main_attribute_3_value' => 'Low Watt, Super PCB',
                'btu_capacity' => 8500,
                'power_consumption_watt' => 810,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Daikin FTKC50TVM4 Premium Inverter',
                'price' => 9800000.00,
                'description' => 'AC Split 2 PK Premium Inverter R32. Kapasitas 17700 BTU, daya 1380 Watt. Teknologi Streamer pemurni udara canggih. Intelligent Eye sensor. Super Powerful mode. Garansi 3 tahun.',
                'category_id' => 8,
                'brand_id' => 1,
                'stock' => 5,
                'img' => 'daikin_ftkc50.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTKC50T',
                'main_attribute_1_name' => 'Pemurni Udara',
                'main_attribute_1_value' => 'Streamer Technology',
                'main_attribute_2_name' => 'Sensor Pintar',
                'main_attribute_2_value' => 'Intelligent Eye',
                'main_attribute_3_name' => 'Mode Pendinginan',
                'main_attribute_3_value' => 'Super Powerful',
                'btu_capacity' => 17700,
                'power_consumption_watt' => 1380,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Daikin FTV25AXV14 Lite Series', // SKU seharusnya berbeda jika model berbeda, misal FTV25
                'price' => 3850000.00,
                'description' => 'AC Split 1 PK Standard R32, kapasitas 9000 BTU, daya 780 Watt. Mode Turbo. Desain minimalis.',
                'category_id' => 6,
                'brand_id' => 1,
                'stock' => 18,
                'img' => 'daikin_ftv25.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTV25AX', // Mengubah SKU agar unik
                'main_attribute_1_name' => 'Garansi',
                'main_attribute_1_value' => '3 Tahun Kompresor',
                'main_attribute_2_name' => 'Ukuran Ruangan',
                'main_attribute_2_value' => '12-16 m²',
                'main_attribute_3_name' => 'Desain',
                'main_attribute_3_value' => 'Minimalis Putih',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 780,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 16,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Daikin FTKC35TVM4 Premium Inverter',
                'price' => 7200000.00,
                'description' => 'AC Split 1.5 PK Premium Inverter R32. Kapasitas 11900 BTU, daya 920 Watt. Teknologi Streamer, Intelligent Eye. Hemat energi superior.',
                'category_id' => 7,
                'brand_id' => 1,
                'stock' => 7,
                'img' => 'daikin_ftkc35.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTKC35T',
                'main_attribute_1_name' => 'Pemurni Udara',
                'main_attribute_1_value' => 'Streamer',
                'main_attribute_2_name' => 'Efisiensi',
                'main_attribute_2_value' => 'Sangat Hemat Energi',
                'main_attribute_3_name' => 'Sensor',
                'main_attribute_3_value' => 'Intelligent Eye',
                'btu_capacity' => 11900,
                'power_consumption_watt' => 920,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],

            // Panasonic (Brand ID 2) - 5 items
            [
                'name' => 'Panasonic CS-PU9XKJ Si-Biru Inverter',
                'price' => 5250000.00,
                'description' => 'AC Split 1 PK Inverter Si-Biru, kapasitas 9000 BTU, daya listrik 824 Watt. Nanoe-G. iAUTO-X. Low Voltage.',
                'category_id' => 6,
                'brand_id' => 2,
                'stock' => 8,
                'img' => 'panasonic_cspu9xkj.jpg',
                'status' => 'available',
                'sku' => 'PNS-CSPU9X',
                'main_attribute_1_name' => 'Filter Udara',
                'main_attribute_1_value' => 'Nanoe-G Anti PM2.5',
                'main_attribute_2_name' => 'Pendinginan Cepat',
                'main_attribute_2_value' => 'iAUTO-X',
                'main_attribute_3_name' => 'Operasi Tegangan Rendah',
                'main_attribute_3_value' => 'Ya',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 824,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Panasonic CS-YN5WKJ Standard',
                'price' => 3200000.00,
                'description' => 'AC Split 1/2 PK Standard, 5000 BTU, daya 390 Watt. Powerful mode. Ecotough outdoor unit.',
                'category_id' => 4,
                'brand_id' => 2,
                'stock' => 20,
                'img' => 'panasonic_csyn5wkj.jpg',
                'status' => 'available',
                'sku' => 'PNS-CSYN5W',
                'main_attribute_1_name' => 'Mode',
                'main_attribute_1_value' => 'Powerful',
                'main_attribute_2_name' => 'Outdoor Unit',
                'main_attribute_2_value' => 'Ecotough Tahan Karat',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R32',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 390,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Panasonic CS-XPU12XKJ Premium Inverter',
                'price' => 7500000.00,
                'description' => 'AC Split 1.5 PK Premium Inverter, 12000 BTU, daya 950 Watt. Nanoe X Technology Mark 2. AEROWINGS. ECO Mode with A.I.',
                'category_id' => 7,
                'brand_id' => 2,
                'stock' => 6,
                'img' => 'panasonic_csxpu12.jpg',
                'status' => 'available',
                'sku' => 'PNS-CSXPU12',
                'main_attribute_1_name' => 'Pemurni Udara',
                'main_attribute_1_value' => 'Nanoe X Mark 2',
                'main_attribute_2_name' => 'Distribusi Udara',
                'main_attribute_2_value' => 'AEROWINGS',
                'main_attribute_3_name' => 'Mode Cerdas',
                'main_attribute_3_value' => 'ECO Mode with A.I.',
                'btu_capacity' => 12000,
                'power_consumption_watt' => 950,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Panasonic CS-LN18WKJ Standard',
                'price' => 6800000.00,
                'description' => 'AC Split 2 PK Standard, 18000 BTU, daya 1660 Watt. Powerful mode. Blue Fin Condenser. R32.',
                'category_id' => 8,
                'brand_id' => 2,
                'stock' => 9,
                'img' => 'panasonic_csln18.jpg',
                'status' => 'available',
                'sku' => 'PNS-CSLN18',
                'main_attribute_1_name' => 'Kondensor',
                'main_attribute_1_value' => 'Blue Fin Anti Karat',
                'main_attribute_2_name' => 'Mode',
                'main_attribute_2_value' => 'Powerful',
                'main_attribute_3_name' => 'Garansi',
                'main_attribute_3_value' => '1 Tahun Sparepart',
                'btu_capacity' => 18000,
                'power_consumption_watt' => 1660,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Panasonic CS-U7XKJ Low Watt',
                'price' => 4100000.00,
                'description' => 'AC Split 3/4 PK Low Watt Series, 7000 BTU, daya hanya 530 Watt. Ecotough. R32.',
                'category_id' => 5,
                'brand_id' => 2,
                'stock' => 11,
                'img' => 'panasonic_csu7.jpg',
                'status' => 'available',
                'sku' => 'PNS-CSU7XKJ',
                'main_attribute_1_name' => 'Tipe',
                'main_attribute_1_value' => 'Low Watt',
                'main_attribute_2_name' => 'Outdoor',
                'main_attribute_2_value' => 'Ecotough',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R32',
                'btu_capacity' => 7000,
                'power_consumption_watt' => 530,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 14,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],

            // LG (Brand ID 3) - 5 items
            [
                'name' => 'LG T10EV4 DualCool Inverter',
                'price' => 4800000.00,
                'description' => 'AC Split 1 PK Inverter hemat energi. Kapasitas 9200 BTU, daya 813 Watt. Watt Control. Active Energy Control.',
                'category_id' => 6,
                'brand_id' => 3,
                'stock' => 12,
                'img' => 'lg_t10ev4.jpg',
                'status' => 'available',
                'sku' => 'LG-T10EV4',
                'main_attribute_1_name' => 'Garansi Kompresor',
                'main_attribute_1_value' => '10 Tahun',
                'main_attribute_2_name' => 'Kontrol Daya',
                'main_attribute_2_value' => 'Watt Control',
                'main_attribute_3_name' => 'Fitur Tambahan',
                'main_attribute_3_value' => 'Active Energy Control',
                'btu_capacity' => 9200,
                'power_consumption_watt' => 813,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'LG H05TN4 New Hercules Standard',
                'price' => 3000000.00,
                'description' => 'AC Split 1/2 PK Standard, 5000 BTU, daya 370 Watt. Turbo Cooling. Anti Korosi Gold Fin. R32.',
                'category_id' => 4,
                'brand_id' => 3,
                'stock' => 22,
                'img' => 'lg_h05tn4.jpg',
                'status' => 'available',
                'sku' => 'LG-H05TN4',
                'main_attribute_1_name' => 'Lapisan Anti Karat',
                'main_attribute_1_value' => 'Gold Fin Condenser',
                'main_attribute_2_name' => 'Pendinginan',
                'main_attribute_2_value' => 'Turbo Cooling',
                'main_attribute_3_name' => 'Daya',
                'main_attribute_3_value' => 'Low Watt',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 370,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'LG T13EV4 DualCool Inverter',
                'price' => 6500000.00,
                'description' => 'AC Split 1.5 PK Inverter. Kapasitas 12000 BTU, daya 1050 Watt. Watt Control. Jet Cool. Garansi kompresor 10 tahun.',
                'category_id' => 7,
                'brand_id' => 3,
                'stock' => 9,
                'img' => 'lg_t13ev4.jpg',
                'status' => 'available',
                'sku' => 'LG-T13EV4',
                'main_attribute_1_name' => 'Garansi',
                'main_attribute_1_value' => '10 Tahun Kompresor',
                'main_attribute_2_name' => 'Fitur',
                'main_attribute_2_value' => 'Jet Cool, Watt Control',
                'main_attribute_3_name' => 'Ionizer',
                'main_attribute_3_value' => 'Tidak Ada',
                'btu_capacity' => 12000,
                'power_consumption_watt' => 1050,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'LG H09TN4 New Hercules Standard',
                'price' => 3700000.00,
                'description' => 'AC Split 1 PK Standard, 9000 BTU, daya 790 Watt. Turbo Cooling. Gold Fin. Hemat Listrik.',
                'category_id' => 6,
                'brand_id' => 3,
                'stock' => 14,
                'img' => 'lg_h09tn4.jpg',
                'status' => 'available',
                'sku' => 'LG-H09TN4',
                'main_attribute_1_name' => 'Anti Karat',
                'main_attribute_1_value' => 'Gold Fin',
                'main_attribute_2_name' => 'Pendinginan',
                'main_attribute_2_value' => 'Turbo',
                'main_attribute_3_name' => 'Efisiensi',
                'main_attribute_3_value' => 'Hemat Listrik',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 790,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'LG P09 portátil',
                'price' => 4200000.00,
                'description' => 'AC Portable 1 PK, 9000 BTU. Mudah dipindahkan. Tidak perlu instalasi outdoor. Remote control.',
                'category_id' => 9,
                'brand_id' => 3,
                'stock' => 5,
                'img' => 'lg_p09.jpg',
                'status' => 'available',
                'sku' => 'LG-P09PORT',
                'main_attribute_1_name' => 'Mobilitas',
                'main_attribute_1_value' => 'Mudah Dipindah',
                'main_attribute_2_name' => 'Instalasi',
                'main_attribute_2_value' => 'Tanpa Outdoor Unit',
                'main_attribute_3_name' => 'Kontrol',
                'main_attribute_3_value' => 'Remote',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 950,
                'is_inverter' => 0,
                'freon_type' => 'R290',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 15,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],

            // Sharp (Brand ID 4) - 5 items
            [
                'name' => 'Sharp AH-A5UCY Turbo Cool',
                'price' => 3100000.00,
                'description' => 'AC Split 1/2 PK Standard Turbo Cool Series. 5000 BTU, Daya 350 Watt (Low Watt). Turbo Cooling, Self Diagnosis.',
                'category_id' => 4,
                'brand_id' => 4,
                'stock' => 25,
                'img' => 'sharp_aha5ucy.jpg',
                'status' => 'available',
                'sku' => 'SHP-A5UCY',
                'main_attribute_1_name' => 'Garansi Kompresor',
                'main_attribute_1_value' => '10 Tahun',
                'main_attribute_2_name' => 'Pendinginan Cepat',
                'main_attribute_2_value' => 'Turbo Cooling',
                'main_attribute_3_name' => 'Fitur Diagnosa',
                'main_attribute_3_value' => 'Self Diagnosis',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 350,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Sharp AH-X9VEY J-Tech Inverter',
                'price' => 5300000.00,
                'description' => 'AC Split 1 PK J-Tech Inverter. 9000 BTU, daya 760 Watt. Plasmacluster Ion. Super Jet Mode. Eco Mode.',
                'category_id' => 6,
                'brand_id' => 4,
                'stock' => 11,
                'img' => 'sharp_ahx9vey.jpg',
                'status' => 'available',
                'sku' => 'SHP-AHX9VEY',
                'main_attribute_1_name' => 'Ionizer',
                'main_attribute_1_value' => 'Plasmacluster HD7000',
                'main_attribute_2_name' => 'Mode Cepat Dingin',
                'main_attribute_2_value' => 'Super Jet Mode',
                'main_attribute_3_name' => 'Mode Hemat',
                'main_attribute_3_value' => 'Eco Mode',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 760,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Sharp AH-A12UCY Turbo Cool',
                'price' => 4500000.00,
                'description' => 'AC Split 1.5 PK Standard Turbo Cool. 12000 BTU, daya 1050 Watt. Powerful Jetstream. Coanda Airflow.',
                'category_id' => 7,
                'brand_id' => 4,
                'stock' => 8,
                'img' => 'sharp_aha12ucy.jpg',
                'status' => 'available',
                'sku' => 'SHP-A12UCY',
                'main_attribute_1_name' => 'Aliran Udara',
                'main_attribute_1_value' => 'Powerful Jetstream, Coanda',
                'main_attribute_2_name' => 'Garansi',
                'main_attribute_2_value' => '10 Tahun Kompresor',
                'main_attribute_3_name' => 'Tipe',
                'main_attribute_3_value' => 'Standard',
                'btu_capacity' => 12000,
                'power_consumption_watt' => 1050,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Sharp AH-A7UCY Low Watt',
                'price' => 3500000.00,
                'description' => 'AC Split 3/4 PK Low Watt, 7000 BTU, daya 540 Watt. Turbo Cooling. Self Cleaning. R32.',
                'category_id' => 5,
                'brand_id' => 4,
                'stock' => 13,
                'img' => 'sharp_aha7ucy.jpg',
                'status' => 'available',
                'sku' => 'SHP-A7UCY',
                'main_attribute_1_name' => 'Fitur Kebersihan',
                'main_attribute_1_value' => 'Self Cleaning X-Fan',
                'main_attribute_2_name' => 'Konsumsi Daya',
                'main_attribute_2_value' => 'Low Watt',
                'main_attribute_3_name' => 'Pendinginan',
                'main_attribute_3_value' => 'Turbo Cooling',
                'btu_capacity' => 7000,
                'power_consumption_watt' => 540,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 14,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Sharp CV-P09GRV-B Portable',
                'price' => 3900000.00,
                'description' => 'AC Portable 1 PK, 9000 BTU. Desain elegan. Mudah dipindahkan. Auto Swing Louver. R410A.',
                'category_id' => 9,
                'brand_id' => 4,
                'stock' => 6,
                'img' => 'sharp_cvp09grv.jpg',
                'status' => 'available',
                'sku' => 'SHP-CVP09GRV',
                'main_attribute_1_name' => 'Tipe AC',
                'main_attribute_1_value' => 'Portable',
                'main_attribute_2_name' => 'Louver',
                'main_attribute_2_value' => 'Auto Swing',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R410A',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 1000,
                'is_inverter' => 0,
                'freon_type' => 'R410A',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 15,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],

            // Samsung (Brand ID 5) - 5 items
            [
                'name' => 'Samsung AR05TYHYDWKNSE WindFree',
                'price' => 4200000.00,
                'description' => 'AC Split 1/2 PK WindFree Inverter. 5000 BTU, daya 485 Watt. Pendinginan tanpa hembusan angin langsung. Digital Inverter Boost. Good Sleep mode.',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 10,
                'img' => 'samsung_ar05ty.jpg',
                'status' => 'available',
                'sku' => 'SMG-AR05TY',
                'main_attribute_1_name' => 'Teknologi',
                'main_attribute_1_value' => 'WindFree Cooling',
                'main_attribute_2_name' => 'Inverter',
                'main_attribute_2_value' => 'Digital Inverter Boost',
                'main_attribute_3_name' => 'Mode Tidur',
                'main_attribute_3_value' => 'Good Sleep',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 485,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Samsung AR09TYHYDWKNSE WindFree',
                'price' => 5500000.00,
                'description' => 'AC Split 1 PK WindFree Inverter. 9000 BTU, daya 820 Watt. WindFree Cooling. Digital Inverter Boost. Triangle Design.',
                'category_id' => 6,
                'brand_id' => 5,
                'stock' => 7,
                'img' => 'samsung_ar09ty.jpg',
                'status' => 'available',
                'sku' => 'SMG-AR09TY',
                'main_attribute_1_name' => 'Desain',
                'main_attribute_1_value' => 'Triangle Design',
                'main_attribute_2_name' => 'Teknologi',
                'main_attribute_2_value' => 'WindFree, Digital Inverter Boost',
                'main_attribute_3_name' => 'Filter',
                'main_attribute_3_value' => 'Easy Filter Plus',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 820,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Samsung AR12TRHLQURNSE Standard',
                'price' => 4300000.00,
                'description' => 'AC Split 1.5 PK Standard R410A. 11500 BTU, daya 1060 Watt. Fast Cool. Good Sleep Mode.',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 11,
                'img' => 'samsung_ar12trh.jpg',
                'status' => 'available',
                'sku' => 'SMG-AR12TRH',
                'main_attribute_1_name' => 'Mode',
                'main_attribute_1_value' => 'Fast Cool, Good Sleep',
                'main_attribute_2_name' => 'Freon',
                'main_attribute_2_value' => 'R410A',
                'main_attribute_3_name' => 'Fitur',
                'main_attribute_3_value' => 'Anti-Korosi DuraFin+',
                'btu_capacity' => 11500,
                'power_consumption_watt' => 1060,
                'is_inverter' => 0,
                'freon_type' => 'R410A',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Samsung AR18TRHLQURNSE Standard',
                'price' => 6700000.00,
                'description' => 'AC Split 2 PK Standard R410A. 17500 BTU, daya 1650 Watt. Fast Cool. Good Sleep Mode. HD Filter.',
                'category_id' => 8,
                'brand_id' => 5,
                'stock' => 6,
                'img' => 'samsung_ar18trh.jpg',
                'status' => 'available',
                'sku' => 'SMG-AR18TRH',
                'main_attribute_1_name' => 'Filter',
                'main_attribute_1_value' => 'HD Filter',
                'main_attribute_2_name' => 'Mode',
                'main_attribute_2_value' => 'Fast Cool, Good Sleep',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R410A',
                'btu_capacity' => 17500,
                'power_consumption_watt' => 1650,
                'is_inverter' => 0,
                'freon_type' => 'R410A',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Samsung AR07NRFLAWKNSE Low Watt',
                'price' => 3700000.00,
                'description' => 'AC Split 3/4 PK Low Watt, 6800 BTU, daya 560 Watt. Triple Protector Plus. Fast Cool. R410A.',
                'category_id' => 5,
                'brand_id' => 5,
                'stock' => 9,
                'img' => 'samsung_ar07nr.jpg',
                'status' => 'available',
                'sku' => 'SMG-AR07NR',
                'main_attribute_1_name' => 'Proteksi',
                'main_attribute_1_value' => 'Triple Protector Plus',
                'main_attribute_2_name' => 'Tipe',
                'main_attribute_2_value' => 'Low Watt',
                'main_attribute_3_name' => 'Mode',
                'main_attribute_3_value' => 'Fast Cool',
                'btu_capacity' => 6800,
                'power_consumption_watt' => 560,
                'is_inverter' => 0,
                'freon_type' => 'R410A',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 14,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],

            // Gree (Brand ID 6) - 5 items
            [
                'name' => 'Gree GWC-05MOO5S Standard MOO5S',
                'price' => 3050000.00,
                'description' => 'AC Split 1/2 PK Standard. 5000 BTU, daya 385 Watt. Frozen Power. Smart Cleaner. Easy Removal. R32.',
                'category_id' => 4,
                'brand_id' => 6,
                'stock' => 16,
                'img' => 'gree_gwc05moo5s.jpg',
                'status' => 'available',
                'sku' => 'GRE-05MOO5S',
                'main_attribute_1_name' => 'Fitur Unggulan',
                'main_attribute_1_value' => 'Frozen Power, Smart Cleaner',
                'main_attribute_2_name' => 'Perawatan',
                'main_attribute_2_value' => 'Easy Removal Filter',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R32',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 385,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Gree GWC-09F5S F5S Inverter',
                'price' => 5100000.00,
                'description' => 'AC Split 1 PK F5S Inverter. 9000 BTU, daya 750 Watt. Fast Cooling "Turbo". Smart WiFi Control. Soft Fan. R32.',
                'category_id' => 6,
                'brand_id' => 6,
                'stock' => 9,
                'img' => 'gree_gwc09f5s.jpg',
                'status' => 'available',
                'sku' => 'GRE-09F5S',
                'main_attribute_1_name' => 'Konektivitas',
                'main_attribute_1_value' => 'Smart WiFi Control',
                'main_attribute_2_name' => 'Kipas',
                'main_attribute_2_value' => 'Soft Fan (Hening)',
                'main_attribute_3_name' => 'Pendinginan',
                'main_attribute_3_value' => 'Fast Cooling Turbo',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 750,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 3,
            ],
            [
                'name' => 'Gree GWC-12MOO5S Standard MOO5S',
                'price' => 4400000.00,
                'description' => 'AC Split 1.5 PK Standard. 12000 BTU, daya 1050 Watt. Frozen Power. Smart Cleaner. Tegangan Rendah 150V. R32.',
                'category_id' => 7,
                'brand_id' => 6,
                'stock' => 7,
                'img' => 'gree_gwc12moo5s.jpg',
                'status' => 'available',
                'sku' => 'GRE-12MOO5S',
                'main_attribute_1_name' => 'Fitur',
                'main_attribute_1_value' => 'Frozen Power, Smart Cleaner',
                'main_attribute_2_name' => 'Tegangan',
                'main_attribute_2_value' => 'Operasi di 150V',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R32',
                'btu_capacity' => 12000,
                'power_consumption_watt' => 1050,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Gree GWC-18MOO5 Standard MOO5S',
                'price' => 6600000.00,
                'description' => 'AC Split 2 PK Standard. 18000 BTU, daya 1700 Watt. Frozen Power. Smart Cleaner. R32.',
                'category_id' => 8,
                'brand_id' => 6,
                'stock' => 4,
                'img' => 'gree_gwc18moo5.jpg',
                'status' => 'available',
                'sku' => 'GRE-18MOO5',
                'main_attribute_1_name' => 'Fitur',
                'main_attribute_1_value' => 'Frozen Power, Smart Cleaner',
                'main_attribute_2_name' => 'Garansi',
                'main_attribute_2_value' => '5 Tahun Kompresor',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R32',
                'btu_capacity' => 18000,
                'power_consumption_watt' => 1700,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Gree GPC-07P1 Portable',
                'price' => 3750000.00,
                'description' => 'AC Portable 3/4 PK, 7000 BTU. Mudah dipindahkan. Roda universal. Sleep Mode. R410A.',
                'category_id' => 9,
                'brand_id' => 6,
                'stock' => 8,
                'img' => 'gree_gpc07p1.jpg',
                'status' => 'available',
                'sku' => 'GRE-GPC07P1',
                'main_attribute_1_name' => 'Tipe',
                'main_attribute_1_value' => 'Portable',
                'main_attribute_2_name' => 'Mode Tidur',
                'main_attribute_2_value' => 'Ya',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R410A',
                'btu_capacity' => 7000,
                'power_consumption_watt' => 780,
                'is_inverter' => 0,
                'freon_type' => 'R410A',
                'room_size_min_sqm' => 9,
                'room_size_max_sqm' => 13,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],

            // Midea (Brand ID 7) - 5 items
            [
                'name' => 'Midea MSFC-05CRN1 Standard',
                'price' => 2800000.00,
                'description' => 'AC Split 1/2 PK Standard. 5000 BTU, daya 396 Watt. Super Cool. Self Cleaning. R32.',
                'category_id' => 4,
                'brand_id' => 7,
                'stock' => 19,
                'img' => 'midea_msfc05crn1.jpg',
                'status' => 'available',
                'sku' => 'MDA-MSFC05',
                'main_attribute_1_name' => 'Pendinginan',
                'main_attribute_1_value' => 'Super Cool Function',
                'main_attribute_2_name' => 'Perawatan',
                'main_attribute_2_value' => 'Self Cleaning',
                'main_attribute_3_name' => 'Lapisan',
                'main_attribute_3_value' => 'Gold Fin Kondensor',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 396,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 2,
            ],
            [
                'name' => 'Midea MSBCU-09CRDN1 Inverter Xtreme Dura',
                'price' => 4500000.00,
                'description' => 'AC Split 1 PK Inverter. 9000 BTU, daya 730 Watt. Xtreme Dura teknologi tahan lama. iECO Mode. Flash Cooling. R32.',
                'category_id' => 6,
                'brand_id' => 7,
                'stock' => 10,
                'img' => 'midea_msbcu09.jpg',
                'status' => 'available',
                'sku' => 'MDA-MSBCU09',
                'main_attribute_1_name' => 'Ketahanan',
                'main_attribute_1_value' => 'Xtreme Dura Technology',
                'main_attribute_2_name' => 'Mode Hemat',
                'main_attribute_2_value' => 'iECO Mode',
                'main_attribute_3_name' => 'Pendinginan Instan',
                'main_attribute_3_value' => 'Flash Cooling',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 730,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 5,
            ],
            [
                'name' => 'Midea MSFO-07CRLN2 Low Watt Forest',
                'price' => 3300000.00,
                'description' => 'AC Split 3/4 PK Low Watt. 7000 BTU, daya 560 Watt. Super Ionizer. Self Cleaning. R32.',
                'category_id' => 5,
                'brand_id' => 7,
                'stock' => 12,
                'img' => 'midea_msfo07.jpg',
                'status' => 'available',
                'sku' => 'MDA-MSFO07',
                'main_attribute_1_name' => 'Ionizer',
                'main_attribute_1_value' => 'Super Ionizer',
                'main_attribute_2_name' => 'Tipe',
                'main_attribute_2_value' => 'Low Watt Forest Series',
                'main_attribute_3_name' => 'Fitur',
                'main_attribute_3_value' => 'Self Cleaning',
                'btu_capacity' => 7000,
                'power_consumption_watt' => 560,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 14,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 2,
            ],
            [
                'name' => 'Midea MSFC-12CRN1 Standard',
                'price' => 4200000.00,
                'description' => 'AC Split 1.5 PK Standard. 12000 BTU, daya 1050 Watt. Super Cool. Self Cleaning. R32.',
                'category_id' => 7,
                'brand_id' => 7,
                'stock' => 8,
                'img' => 'midea_msfc12.jpg',
                'status' => 'available',
                'sku' => 'MDA-MSFC12',
                'main_attribute_1_name' => 'Pendinginan',
                'main_attribute_1_value' => 'Super Cool',
                'main_attribute_2_name' => 'Fitur',
                'main_attribute_2_value' => 'Self Cleaning',
                'main_attribute_3_name' => 'Freon',
                'main_attribute_3_value' => 'R32',
                'btu_capacity' => 12000,
                'power_consumption_watt' => 1050,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 2,
            ],
            [
                'name' => 'Midea MPF2-12CRN1 Portable',
                'price' => 4000000.00,
                'description' => 'AC Portable 1.5 PK, 12000 BTU. Mudah dipindahkan. Remote. Sleep mode. R410A.',
                'category_id' => 9,
                'brand_id' => 7,
                'stock' => 5,
                'img' => 'midea_mpf212.jpg',
                'status' => 'available',
                'sku' => 'MDA-MPF212',
                'main_attribute_1_name' => 'Tipe',
                'main_attribute_1_value' => 'Portable',
                'main_attribute_2_name' => 'Kapasitas',
                'main_attribute_2_value' => '1.5 PK',
                'main_attribute_3_name' => 'Mode Tidur',
                'main_attribute_3_value' => 'Ya',
                'btu_capacity' => 12000,
                'power_consumption_watt' => 1200,
                'is_inverter' => 0,
                'freon_type' => 'R410A',
                'room_size_min_sqm' => 15,
                'room_size_max_sqm' => 20,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],

            // 10 DATA TAMBAHAN YANG SUDAH DIBUAT SEBELUMNYA
            [
                'name' => 'Daikin FTKM35SVM4 European Design Inverter',
                'price' => 8200000.00,
                'description' => 'AC Split 1.5 PK Inverter, desain stylish Eropa. Kapasitas 11900 BTU, daya 920 Watt. Gin-Ion Blue Filter, Power Chill Operation, R32.',
                'category_id' => 7,
                'brand_id' => 1,
                'stock' => 8,
                'img' => 'daikin_ftkm35.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTKM35S',
                'main_attribute_1_name' => 'Desain',
                'main_attribute_1_value' => 'European Stylish',
                'main_attribute_2_name' => 'Filter Udara',
                'main_attribute_2_value' => 'Gin-Ion Blue Filter',
                'main_attribute_3_name' => 'Pendinginan Cepat',
                'main_attribute_3_value' => 'Power Chill',
                'btu_capacity' => 11900,
                'power_consumption_watt' => 920,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Panasonic CS-YN7WKJ Standard',
                'price' => 3500000.00,
                'description' => 'AC Split 3/4 PK Standard, 7000 BTU, daya 650 Watt. Powerful mode. Ecotough outdoor. R32.',
                'category_id' => 5,
                'brand_id' => 2,
                'stock' => 15,
                'img' => 'panasonic_csyn7wkj.jpg',
                'status' => 'available',
                'sku' => 'PNS-CSYN7W',
                'main_attribute_1_name' => 'Kapasitas',
                'main_attribute_1_value' => '3/4 PK',
                'main_attribute_2_name' => 'Mode Pendinginan',
                'main_attribute_2_value' => 'Powerful',
                'main_attribute_3_name' => 'Outdoor',
                'main_attribute_3_value' => 'Ecotough Anti Karat',
                'btu_capacity' => 7000,
                'power_consumption_watt' => 650,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 14,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'LG T19EV5 DualCool ThinQ Inverter',
                'price' => 9300000.00,
                'description' => 'AC Split 2 PK Inverter dengan ThinQ (WiFi). Kapasitas 18000 BTU, daya 1600 Watt. Watt Control, Active Energy Control. Garansi kompresor 10 tahun.',
                'category_id' => 8,
                'brand_id' => 3,
                'stock' => 6,
                'img' => 'lg_t19ev5.jpg',
                'status' => 'available',
                'sku' => 'LG-T19EV5',
                'main_attribute_1_name' => 'Konektivitas',
                'main_attribute_1_value' => 'ThinQ WiFi Control',
                'main_attribute_2_name' => 'Garansi',
                'main_attribute_2_value' => '10 Tahun Kompresor',
                'main_attribute_3_name' => 'Kontrol Energi',
                'main_attribute_3_value' => 'Watt Control',
                'btu_capacity' => 18000,
                'power_consumption_watt' => 1600,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Sharp AH-XP6SHY J-Tech Inverter Plasmacluster',
                'price' => 4400000.00,
                'description' => 'AC Split 1/2 PK J-Tech Inverter. 5000 BTU, daya 390 Watt. Plasmacluster Ion Generator. Super Jet Mode. Garansi 10 tahun kompresor.',
                'category_id' => 4,
                'brand_id' => 4,
                'stock' => 18,
                'img' => 'sharp_ahxp6shy.jpg',
                'status' => 'available',
                'sku' => 'SHP-AHXP6SHY',
                'main_attribute_1_name' => 'Teknologi Ion',
                'main_attribute_1_value' => 'Plasmacluster Generator',
                'main_attribute_2_name' => 'Tipe Inverter',
                'main_attribute_2_value' => 'J-Tech Inverter',
                'main_attribute_3_name' => 'Mode Dingin Cepat',
                'main_attribute_3_value' => 'Super Jet Mode',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 390,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Samsung AR12TYEAAWKNSE WindFree Comfort',
                'price' => 7100000.00,
                'description' => 'AC Split 1.5 PK WindFree Inverter Comfort. 11500 BTU, daya 1020 Watt. WindFree Cooling, AI Auto Cooling, Easy Filter Plus. R32.',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 9,
                'img' => 'samsung_ar12tyeaa.jpg',
                'status' => 'available',
                'sku' => 'SMG-AR12TYEAA',
                'main_attribute_1_name' => 'Pendinginan Cerdas',
                'main_attribute_1_value' => 'AI Auto Cooling',
                'main_attribute_2_name' => 'Tanpa Hembusan',
                'main_attribute_2_value' => 'WindFree Comfort',
                'main_attribute_3_name' => 'Filter Anti Bakteri',
                'main_attribute_3_value' => 'Easy Filter Plus',
                'btu_capacity' => 11500,
                'power_consumption_watt' => 1020,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 18,
                'room_size_max_sqm' => 24,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Gree GWC-07MOO5S Standard MOO5S',
                'price' => 3350000.00,
                'description' => 'AC Split 3/4 PK Standard. 7000 BTU, daya 630 Watt. Frozen Power. Smart Cleaner. Low Voltage. R32.',
                'category_id' => 5,
                'brand_id' => 6,
                'stock' => 14,
                'img' => 'gree_gwc07moo5s.jpg',
                'status' => 'available',
                'sku' => 'GRE-07MOO5S',
                'main_attribute_1_name' => 'Fitur Pendinginan',
                'main_attribute_1_value' => 'Frozen Power',
                'main_attribute_2_name' => 'Operasi Tegangan Rendah',
                'main_attribute_2_value' => 'Ya, hingga 150V',
                'main_attribute_3_name' => 'Perawatan Otomatis',
                'main_attribute_3_value' => 'Smart Cleaner',
                'btu_capacity' => 7000,
                'power_consumption_watt' => 630,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 14,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Midea MSAF-09CRN1 Standard Low Watt',
                'price' => 3200000.00,
                'description' => 'AC Split 1 PK Standard Low Watt. 9000 BTU, daya 690 Watt. Super Cool. Self Cleaning. Gold Fin. R32.',
                'category_id' => 6,
                'brand_id' => 7,
                'stock' => 20,
                'img' => 'midea_msaf09crn1.jpg',
                'status' => 'available',
                'sku' => 'MDA-MSAF09LW',
                'main_attribute_1_name' => 'Tipe Daya',
                'main_attribute_1_value' => 'Low Watt',
                'main_attribute_2_name' => 'Pendinginan Cepat',
                'main_attribute_2_value' => 'Super Cool',
                'main_attribute_3_name' => 'Lapisan Anti Karat',
                'main_attribute_3_value' => 'Gold Fin Evaporator & Kondensor',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 690,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 2,
            ],
            [
                'name' => 'Daikin FTV50CXV14 Standard Thailand',
                'price' => 7600000.00,
                'description' => 'AC Split 2 PK Standard Thailand. Kapasitas 18000 BTU, daya 1750 Watt. Mode Turbo. Filter Saranet. R32.',
                'category_id' => 8,
                'brand_id' => 1,
                'stock' => 7,
                'img' => 'daikin_ftv50cxv.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTV50CXV',
                'main_attribute_1_name' => 'Buatan',
                'main_attribute_1_value' => 'Thailand',
                'main_attribute_2_name' => 'Kapasitas Besar',
                'main_attribute_2_value' => '2 PK Standard',
                'main_attribute_3_name' => 'Filter Debu',
                'main_attribute_3_value' => 'Saranet Filter',
                'btu_capacity' => 18000,
                'power_consumption_watt' => 1750,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'LG P07 portátil',
                'price' => 3800000.00,
                'description' => 'AC Portable 3/4 PK, 7000 BTU. Desain kompak, mudah dipindah. Mode tidur. Remote Control. R290.',
                'category_id' => 9,
                'brand_id' => 3,
                'stock' => 4,
                'img' => 'lg_p07.jpg',
                'status' => 'available',
                'sku' => 'LG-P07PORT',
                'main_attribute_1_name' => 'Ukuran PK',
                'main_attribute_1_value' => '3/4 PK Portable',
                'main_attribute_2_name' => 'Fitur',
                'main_attribute_2_value' => 'Mode Tidur, Remote',
                'main_attribute_3_name' => 'Freon Ramah Lingkungan',
                'main_attribute_3_value' => 'R290',
                'btu_capacity' => 7000,
                'power_consumption_watt' => 800,
                'is_inverter' => 0,
                'freon_type' => 'R290',
                'room_size_min_sqm' => 9,
                'room_size_max_sqm' => 13,
                'warranty_compressor_years' => 1,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Sharp AH-A18UCY Turbo Cool',
                'price' => 6900000.00,
                'description' => 'AC Split 2 PK Standard Turbo Cool. 18000 BTU, daya 1640 Watt. Powerful Jetstream. Coanda Airflow. Garansi Kompresor 10 Tahun.',
                'category_id' => 8,
                'brand_id' => 4,
                'stock' => 7,
                'img' => 'sharp_aha18ucy.jpg',
                'status' => 'available',
                'sku' => 'SHP-A18UCY',
                'main_attribute_1_name' => 'Pendinginan Ekstra Cepat',
                'main_attribute_1_value' => 'Powerful Jetstream',
                'main_attribute_2_name' => 'Aliran Udara Nyaman',
                'main_attribute_2_value' => 'Coanda Airflow',
                'main_attribute_3_name' => 'Garansi Panjang',
                'main_attribute_3_value' => '10 Tahun Kompresor',
                'btu_capacity' => 18000,
                'power_consumption_watt' => 1640,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],

            // 5 DATA TAMBAHAN BARU (untuk mencapai 50)
            [
                'name' => 'Samsung AR24TYHQASINSE WindFree Premium Plus',
                'price' => 12500000.00,
                'description' => 'AC Split 2.5 PK (setara) WindFree Inverter Premium. Kapasitas 22000 BTU, daya 1950 Watt. WindFree Cooling, AI Auto Cooling, Tri-Care Filter. R32.',
                'category_id' => 8, // Menggunakan kategori 2 PK, tapi BTU lebih tinggi
                'brand_id' => 5, // Samsung
                'stock' => 4,
                'img' => 'samsung_ar24tyhqa.jpg',
                'status' => 'available',
                'sku' => 'SMG-AR24TYHQA',
                'main_attribute_1_name' => 'Kapasitas Super',
                'main_attribute_1_value' => '22000 BTU (Setara 2.5 PK)',
                'main_attribute_2_name' => 'Filter Premium',
                'main_attribute_2_value' => 'Tri-Care Filter Anti Virus',
                'main_attribute_3_name' => 'Kenyamanan Cerdas',
                'main_attribute_3_value' => 'WindFree + AI Auto Cooling',
                'btu_capacity' => 22000,
                'power_consumption_watt' => 1950,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 30, // Disesuaikan dengan BTU
                'room_size_max_sqm' => 40, // Disesuaikan dengan BTU
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Gree GWC-09MOO5X Deluxe Standard',
                'price' => 3600000.00,
                'description' => 'AC Split 1 PK Standard Deluxe. 9000 BTU, daya 800 Watt. Self-Cleaning Plus, Gold Fin Condenser, Turbo Mode. R32.',
                'category_id' => 6, // 1 PK
                'brand_id' => 6, // Gree
                'stock' => 12,
                'img' => 'gree_gwc09moo5x.jpg',
                'status' => 'available',
                'sku' => 'GRE-09MOO5X',
                'main_attribute_1_name' => 'Pembersihan Otomatis',
                'main_attribute_1_value' => 'Self-Cleaning Plus',
                'main_attribute_2_name' => 'Lapisan Pelindung',
                'main_attribute_2_value' => 'Gold Fin Anti Karat',
                'main_attribute_3_name' => 'Mode Cepat',
                'main_attribute_3_value' => 'Turbo Mode',
                'btu_capacity' => 9000,
                'power_consumption_watt' => 800,
                'is_inverter' => 0,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 12,
                'room_size_max_sqm' => 18,
                'warranty_compressor_years' => 5,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Midea MSBCU-05BL Blanc Inverter',
                'price' => 3900000.00,
                'description' => 'AC Split 1/2 PK Blanc Series Inverter. 5000 BTU, daya 380 Watt. Desain elegan, Super Cool, iECO Mode. R32.',
                'category_id' => 4, // 1/2 PK
                'brand_id' => 7, // Midea
                'stock' => 10,
                'img' => 'midea_msbcu05bl.jpg',
                'status' => 'available',
                'sku' => 'MDA-MSBCU05BL',
                'main_attribute_1_name' => 'Desain Premium',
                'main_attribute_1_value' => 'Blanc Series Putih Elegan',
                'main_attribute_2_name' => 'Hemat Energi',
                'main_attribute_2_value' => 'iECO Mode Inverter',
                'main_attribute_3_name' => 'Pendinginan Instan',
                'main_attribute_3_value' => 'Super Cool',
                'btu_capacity' => 5000,
                'power_consumption_watt' => 380,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 6,
                'room_size_max_sqm' => 10,
                'warranty_compressor_years' => 10,
                'warranty_parts_years' => 5,
            ],
            [
                'name' => 'Panasonic CS-PU18XKJ Si-Biru Inverter 2PK',
                'price' => 8800000.00,
                'description' => 'AC Split 2 PK Inverter Si-Biru. Kapasitas 18000 BTU, daya 1550 Watt. Nanoe-G, iAUTO-X, ECO Mode. R32.',
                'category_id' => 8, // 2 PK
                'brand_id' => 2, // Panasonic
                'stock' => 7,
                'img' => 'panasonic_cspu18xkj.jpg',
                'status' => 'available',
                'sku' => 'PNS-CSPU18X', // Memastikan SKU unik
                'main_attribute_1_name' => 'Udara Bersih',
                'main_attribute_1_value' => 'Nanoe-G Filter',
                'main_attribute_2_name' => 'Pendinginan Optimal',
                'main_attribute_2_value' => 'iAUTO-X & ECO Mode',
                'main_attribute_3_name' => 'Kapasitas',
                'main_attribute_3_value' => '2 PK Inverter',
                'btu_capacity' => 18000,
                'power_consumption_watt' => 1550,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 28,
                'room_size_max_sqm' => 36,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
            [
                'name' => 'Daikin FTKQ20UVM4 Star Inverter 3/4 PK',
                'price' => 4850000.00,
                'description' => 'AC Split 3/4 PK Star Inverter R32. Kapasitas 7100 BTU, daya 580 Watt. Gin-Ion Filter, Mode Low Watt. Hemat Listrik.',
                'category_id' => 5, // 3/4 PK
                'brand_id' => 1, // Daikin
                'stock' => 11,
                'img' => 'daikin_ftkq20u.jpg',
                'status' => 'available',
                'sku' => 'DKN-FTKQ20U',
                'main_attribute_1_name' => 'Ukuran Efisien',
                'main_attribute_1_value' => '3/4 PK Star Inverter',
                'main_attribute_2_name' => 'Filter Kesehatan',
                'main_attribute_2_value' => 'Gin-Ion Anti Bakteri',
                'main_attribute_3_name' => 'Operasi Hemat',
                'main_attribute_3_value' => 'Mode Low Watt',
                'btu_capacity' => 7100,
                'power_consumption_watt' => 580,
                'is_inverter' => 1,
                'freon_type' => 'R32',
                'room_size_min_sqm' => 10,
                'room_size_max_sqm' => 14,
                'warranty_compressor_years' => 3,
                'warranty_parts_years' => 1,
            ],
        ];

        // Tambahkan created_at dan updated_at ke setiap item
        foreach ($itemsData as &$item) { // Gunakan reference agar bisa diubah
            $item['created_at'] = now();
            $item['updated_at'] = now();
        }
        unset($item); // Hapus reference

        Item::insert($itemsData);
    }
}
